---
- hosts: all
  become: true
  tasks:
    - name: Install list of packages
      apt: name='{{item}}' state=present
      with_items:
       - apache2
       - wget
       - vim
       - zip
       - unzip
