---
- hosts: 192.168.56.6
  become: true
  vars:
    technology: aws
    city: hyderabad
    devops: jenkins
  tasks:
   - name: install apache2
     apt:
       name: apache2
       state: present
   - name: start apache service
     service:
       name: apache2
       state: started
   - name: copy the files
     template:
       src: index.html
       dest: /var/www/html/index.html
